name: photoview

services:
  ui:
    image: photoview/ui
    build:
      context: .
      dockerfile: Dockerfile
      target: ui
      args:
        - NODE_ENV=development
    env_file: ui/example.env
    volumes:
      - .:/app:rw
    ports:
      - 1234:1234
    command:
      - /bin/bash
      - -c
      - |
        npm ci
        npm run mon

  api:
    image: photoview/api
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    env_file: api/example.env
    environment:
      PHOTOVIEW_DATABASE_DRIVER: mysql # Change to the right database driver
      ##PHOTOVIEW_SQLITE_PATH: photoview.db
      ##PHOTOVIEW_MYSQL_URL: photoview:photosecret@tcp(mariadb)/photoview_test
      PHOTOVIEW_MYSQL_URL: photoview:photosecret@tcp(mariadb)/${MARIADB_DATABASE}
    volumes:
      - .:/app:rw
      - ./photos:/photos:ro
    ports:
      - 4001:4001
    command:
      - /bin/bash
      - -c
      - |
        export $(cat /env)
        reflex -g '*.go' -s -- go run .

  mariadb:
    image: mariadb:lts
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    hostname: photoview-mariadb
    container_name: photoview-mariadb
    stop_grace_period: 5s
    command: mariadbd --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    security_opt: ## see https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1136151239
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      #MARIADB_AUTO_UPGRADE: "1"
      ##MYSQL_DATABASE: photoview_test
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: photoview
      #MARIADB_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: photosecret
      #MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      #MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - "/etc/localtime:/etc/localtime:ro" ## use local time from host
      - "/etc/timezone:/etc/timezone:ro"   ## use timezone from host
      - "${HOST_PHOTOVIEW_LOCATION}/database/mariadb:/var/lib/mysql" ## DO NOT REMOVE
    healthcheck:
      test:
        - CMD
        - mariadb-admin
        - --user=photoview
        - --password=photosecret
        - ping
      #test: healthcheck.sh --connect --innodb_initialized
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 3m
    expose:
      - "3306"

