package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"log"
	"os"

	"github.com/loiuscypher/photoview/api/graphql/models"
	"github.com/loiuscypher/photoview/api/scanner/face_detection"
	"gopkg.in/gographics/imagick.v3/imagick"
	"gorm.io/gorm"
)

// ExportAllFaces is the resolver for the exportAllFaces field.
func (r *mutationResolver) ExportAllFaces(ctx context.Context) (*models.DevCmdResult, error) {
	log.Printf("ExportAllFaces\n")
	return r.ExportFaces(ctx, false)
}

// ExportFaces is the resolver for the exportFaces field.
func (r *mutationResolver) ExportFaces(ctx context.Context, onlyConfirmed bool) (*models.DevCmdResult, error) {
	log.Printf("ExportFaces: %b\n", onlyConfirmed)
	db := r.DB(ctx)
	var selectedImageFaces []*models.ImageFace
	if onlyConfirmed {
		if result := db.Find(&selectedImageFaces, "Confirmed = TRUE").Order("FaceGroupID asc, MediaID asc, ID"); result.Error != nil {
			return nil, fmt.Errorf("get confirmed imageFaces from database: %w", result.Error)
		}
		log.Printf(" onlyConfirmed Face Count: %d\n", len(selectedImageFaces))
	} else {
		if result := db.Find(&selectedImageFaces).Order("Confirmed asc, FaceGroupID asc, MediaID asc, ID"); result.Error != nil {
			return nil, fmt.Errorf("get imageFaces from database: %w", result.Error)
		}
		log.Printf("All Face Count: %d\n", len(selectedImageFaces))
	}

	imagick.Initialize()
	defer imagick.Terminate()

	for i, face := range selectedImageFaces {
		log.Printf("Index %d Face ID: %d  FaceGroupID: %d\n", i, face.ID, face.FaceGroupID)
		if err := face.FillMedia(db); err != nil {
			log.Printf("Err: FillMedia %s\n", err)
			continue
		}
		log.Printf(" Media: %d %s  URL Count: %d subgroup: %03d confirmed: %5t Rectangle: %f %f %f %f\n", face.Media.ID, face.Media.Path, len(face.Media.MediaURL), face.Subgroup, face.Confirmed, face.Rectangle.MinX, face.Rectangle.MaxX, face.Rectangle.MinY, face.Rectangle.MaxY)

		mw := imagick.NewMagickWand()
		defer mw.Destroy()
		if err := mw.ReadImage(face.Media.Path); err != nil {
			log.Printf("Err: ReadImage %s\n", err)
			continue
		}
		if err := mw.AutoOrientImage(); err != nil {
			log.Printf("Err: AutoOrientImage %s\n", err)
			continue
		}
		if err := mw.StripImage(); err != nil {
			log.Printf("Err: StripImage %s\n", err)
			continue
		}
		// const framing_factor = 0.025
		const framing_factor = 0.05
		width := mw.GetImageWidth()
		// x := int(float64(width) * (1.0 - framing_factor) * face.Rectangle.MinX)
		height := mw.GetImageHeight()
		// y := int(float64(height) * (1.0 - framing_factor) * face.Rectangle.MinY)
		// f_width := uint(int(float64(width)*(1.0+2.0*framing_factor)*face.Rectangle.MaxX) - x)
		// f_height := uint(int(float64(height)*(1.0+2.0*framing_factor)*face.Rectangle.MaxY) - y)
		// log.Printf(" Width: %d  Height: %d  X: %d  Y: %d  Width: %d  Height: %d\n", width, height, x, y, f_height, f_width)

		// Y_width_perc := face.Rectangle.MaxX - face.Rectangle.MinX
		// f_height_perc := face.Rectangle.MaxY - face.Rectangle.MinY

		// f_scaled_w_perc := (1.0 + 2 * framing_factor) * f_width_perc
		f_scaled_w_perc := (1.0 + 2*framing_factor) * (face.Rectangle.MaxX - face.Rectangle.MinX)
		// if f_scaled_w_perc != ((1.0 + 2*framing_factor) * f_width_perc) {
		// 	log.Printf("   Err f_scaled_w_perc: %f != %f\n", f_scaled_w_perc, (1.0+2*framing_factor)*f_width_perc)
		// }
		// f_scaled_h_perc := (1.0 + 2*framing_factor) * f_height_perc
		f_scaled_h_perc := (1.0 + 2*framing_factor) * (face.Rectangle.MaxY - face.Rectangle.MinY)

		// f_center_x_perc := face.Rectangle.MinX + f_width_perc / 2
		// f_center_x_perc := face.Rectangle.MinX/2 + face.Rectangle.MaxX/2
		// if f_center_x_perc != (face.Rectangle.MinX + f_width_perc/2) {
		// 	log.Printf("   Err f_center_x_perc: %f != %f\n", f_center_x_perc, face.Rectangle.MinX+f_width_perc/2)
		// }
		// f_center_y_perc := face.Rectangle.MinY + f_height_perc/2

		// f_scaled_x_perc := f_center_x_perc - f_scaled_w_perc / 2
		f_scaled_x_perc := (1.0+framing_factor)*face.Rectangle.MinX - face.Rectangle.MaxX*framing_factor
		// if f_scaled_x_perc != (f_center_x_perc - f_scaled_w_perc/2) {
		// 	log.Printf("   Err f_scaled_x_perc: %f != %f diff: %f\n", f_scaled_x_perc, f_center_x_perc-f_scaled_w_perc/2, f_scaled_x_perc-(f_center_x_perc-f_scaled_w_perc/2))
		// }
		// f_scaled_y_perc := f_center_y_perc - f_scaled_h_perc/2
		f_scaled_y_perc := (1.0+framing_factor)*face.Rectangle.MinY - face.Rectangle.MaxY*framing_factor

		f_scaled_x := int(float64(width) * f_scaled_x_perc)
		f_scaled_y := int(float64(height) * f_scaled_y_perc)
		f_scaled_w := uint(float64(width) * f_scaled_w_perc)
		f_scaled_h := uint(float64(height) * f_scaled_h_perc)
		log.Printf(" Width: %d  Height: %d  X: %d  Y: %d  Width: %d  Height: %d\n", width, height, f_scaled_x, f_scaled_y, f_scaled_h, f_scaled_w)

		// if f_scaled_x != x {
		// 	log.Printf("   ERR f_scaled_x: %d != %d\n", f_scaled_x, x)
		// }
		// if f_scaled_y != y {
		// 	log.Printf("   ERR f_scaled_y: %d != %d\n", f_scaled_y, y)
		// }
		// if f_scaled_w != f_width {
		// 	log.Printf("   ERR f_scaled_y: %d != %d\n", f_scaled_w, f_width)
		// }
		// if f_scaled_h != f_height {
		// 	log.Printf("   ERR f_scaled_y: %d != %d\n", f_scaled_h, f_height)
		// }

		if err := mw.CropImage(f_scaled_w, f_scaled_h, f_scaled_x, f_scaled_y); err != nil {
		// if err := mw.CropImage(f_width, f_height, x, y); err != nil {
			log.Printf("Err: CropImage %s\n", err)
			continue
		}
		if err := mw.SetImagePage(f_scaled_w, f_scaled_h, f_scaled_x, f_scaled_y); err != nil {
		// if err := mw.SetImagePage(f_width, f_height, x, y); err != nil {
			log.Printf("Err: SetImagePage %s\n", err)
			continue
		}
		r_name := "/home/photoview/media-cache/portraits"
		var confirmSuffix = "confirmed"
		if !face.Confirmed {
			confirmSuffix = "unsure"
		}

		lb := ""
		var faceGroup models.FaceGroup
		if err := db.
			// Debug().
			Model(models.FaceGroup{}).
			Where("id = ?", face.FaceGroupID).
			First(&faceGroup).
			Error; err == nil {

			log.Printf("FaceGroup ok\n")
			if faceGroup.Label != nil {
				log.Printf("FaceGroup,Label %s\n", *faceGroup.Label)
				lb = *faceGroup.Label
			}
		}

		d_name := fmt.Sprintf("%s/%08d_%03d_%s-%s", r_name, face.FaceGroupID, -face.Subgroup, lb, confirmSuffix)
		if err := os.MkdirAll(d_name, 0775); err != nil {

			log.Printf("Err: MkdirAll %s\n", err)
			continue
		}
		if !onlyConfirmed {
			s_name := fmt.Sprintf("%s/%06d_%06d_%04d_%04d_%04d_%04d-s.jpg", r_name, face.Media.ID, face.ID, f_scaled_w, f_scaled_h, f_scaled_x, f_scaled_y)
			if err := mw.WriteImage(s_name); err != nil {
				log.Printf("Err: WriteImage %s\n", err)
				continue
			}
		}
		f_name := fmt.Sprintf("%s/%06d_%06d_%04d_%04d_%04d_%04d-s.jpg", d_name, face.Media.ID, face.ID, f_scaled_w, f_scaled_h, f_scaled_x, f_scaled_y)
		log.Printf(" Filename: %s\n", f_name)
		if err := mw.WriteImage(f_name); err != nil {
			log.Printf("Err: WriteImage %s\n", err)
			continue
		}

		/*
			if face.Media.MediaURL == nil {
				if err := db.Model(&face.Media).Association("MediaURL").Find(&face.Media.MediaURL); err != nil {
					log.Printf("Err: %w\n", err)
					continue
				}

			}

			for _, url := range face.Media.MediaURL {
				log.Printf("  Media URL: %s %s\n", url.URL(), url.Purpose)
			}
		*/
	}
	log.Printf("Export done. Count: %d\n", len(selectedImageFaces))

	startMessage := "Export faces Done"
	return &models.DevCmdResult{
		Success: true,
		Message: &startMessage,
	}, nil
}

// CheckFaceGroup is the resolver for the checkFaceGroup field.
func (r *mutationResolver) CheckFaceGroup(ctx context.Context, faceGroupID int) (*models.DevCmdResult, error) {
	face_detection.GlobalFaceDetector.CheckFaceGroup(r.DB(ctx), int32(faceGroupID))

	startMessage := "Check face group Done"
	return &models.DevCmdResult{
		Success: true,
		Message: &startMessage,
	}, nil
}

// SetFaceClassifyThreshold is the resolver for the setFaceClassifyThreshold field.
func (r *mutationResolver) SetFaceClassifyThreshold(ctx context.Context, threshold float64) (float64, error) {
	log.Printf("SetFaceClassifyThreshold: %f\n", threshold)
	db := r.DB(ctx)
	if err := db.
		Session(&gorm.Session{AllowGlobalUpdate: true}).
		Model(&models.SiteInfo{}).
		Update("classify_face_threshold", threshold).
		Error; err != nil {

		return 0, err
	}

	var siteInfo models.SiteInfo
	if err := db.First(&siteInfo).Error; err != nil {
		return 0, err
	}

	face_detection.GlobalFaceDetector.ChangeClassifyFaceThreshold(float32(siteInfo.ClassifyFaceThreshold))

	return siteInfo.ClassifyFaceThreshold, nil
}

// SplitFaceGroup
func (r *mutationResolver) SplitFaceGroup(ctx context.Context, groupID int) (*models.DevCmdResult, error) {
	log.Printf("SplitFaceGroup: %d\n", groupID)
	face_detection.GlobalFaceDetector.SplitFaceGroup(r.DB(ctx), int32(groupID))

	startMessage := "Split face group Done"
	return &models.DevCmdResult{
		Success: true,
		Message: &startMessage,
	}, nil
}

// ToggleConfirmFaceGroup is the resolver for the toggleConfirmFaceGroup field.
func (r *mutationResolver) ToggleConfirmFaceGroup(ctx context.Context, imageFaceID int) (bool, error) {
	db := r.DB(ctx)

	if err := db.
		Where("id = ?", imageFaceID).
		Model(&models.ImageFace{}).
		UpdateColumn("confirmed", gorm.Expr("NOT confirmed")).
		Error; err != nil {

		return false, err
	}

	var confirmed bool
	if err := db.
		Where("id = ?", imageFaceID).
		Model(&models.ImageFace{}).
		Pluck("confirmed", &confirmed).
		Error; err != nil {

		return false, err
	}

	return confirmed, nil
}
