package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"log"
	"time"

	api "github.com/loiuscypher/photoview/api/graphql"
	"github.com/loiuscypher/photoview/api/graphql/auth"
	"github.com/loiuscypher/photoview/api/graphql/models"
	"github.com/loiuscypher/photoview/api/scanner/face_detection"
	"github.com/loiuscypher/photoview/api/utils"
	"gorm.io/gorm"
)

var sum1Is time.Duration
var sum2Is time.Duration
var sum1Cs time.Duration
var sum2Cs time.Duration
var sum1Ms time.Duration
var sum2Ms time.Duration

// ImageFaces is the resolver for the imageFaces field.
func (r *faceGroupResolver) ImageFaces(ctx context.Context, obj *models.FaceGroup, paginate *models.Pagination) ([]*models.ImageFace, error) {
	//log.Println("TRACE ImageFaces", obj)
	db := r.DB(ctx)
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, errors.New("unauthorized")
	}

	if face_detection.GlobalFaceDetector == nil {
		return nil, ErrFaceDetectorNotInitialized
	}
	begin1 := time.Now()
	var count int
	if utils.DevelopmentCheckSqlTiming() {
		if err := user.FillAlbums(db); err != nil {
			return nil, err
		}

		userAlbumIDs := make([]int, len(user.Albums))
		for i, album := range user.Albums {
			userAlbumIDs[i] = album.ID
		}

		query := db.
			Joins("Media").
			Where(faceGroupIDIsQuestion, obj.ID).
			Where("album_id IN (?)", userAlbumIDs).
			Order("subgroup ASC").
			Order("confirmed DESC")

		query = models.FormatSQL(query, nil, paginate)

		var imageFaces []*models.ImageFace
		if err := query.Find(&imageFaces).Error; err != nil {
			return nil, err
		}
		count = len(imageFaces)
	}
	time1 := time.Since(begin1)
	//log.Println("FaceGroup1", faceGroup.ID, "Time1", time1)
//////////////////////////////////////
	begin2 := time.Now()
	query2 := db.
		Joins("Media").
		Joins("JOIN user_albums ON user_albums.album_id = Media.album_id").Where("user_albums.user_id = ?", user.ID).
		Where(faceGroupIDIsQuestion, obj.ID).
		Order("subgroup ASC").
		Order("confirmed DESC")

	query2 = models.FormatSQL(query2, nil, paginate)

	var imageFaces2 []*models.ImageFace
	if err := query2.Find(&imageFaces2).Error; err != nil {
		return nil, err
	}
	if utils.DevelopmentCheckSqlTiming() {
		time2 := time.Since(begin2)
		sum1Is += time1
		sum2Is += time2
		if count != len(imageFaces2) {
			log.Println("ERROR ImageFaces len", count, "!=", len(imageFaces2))
		} else {
			log.Println("TRACE ImageFaces len", len(imageFaces2), "Time1", time1, "Time2", time2, "Diff", time1 - time2)
			log.Println("TRACE DiffCs", sum1Cs - sum2Cs, "Sum1Cs", sum1Cs, "Sum2Cs", sum2Cs, "Diff %", 100 * float64(sum1Cs - sum2Cs) / float64(sum1Cs) )
			log.Println("TRACE DiffIs", sum1Is - sum2Is, "Sum1Is", sum1Is, "Sum2Is", sum2Is, "Diff %", 100 * float64(sum1Is - sum2Is) / float64(sum1Is) )
			log.Println("TRACE DiffMs", sum1Ms - sum2Ms, "Sum1Ms", sum1Ms, "Sum2Ms", sum2Ms, "Diff %", 100 * float64(sum1Ms - sum2Ms) / float64(sum1Ms) )
		}
	}
//////////////////////////////////////

	return imageFaces2, nil
}

// ImageFaceCount is the resolver for the imageFaceCount field.
func (r *faceGroupResolver) ImageFaceCount(ctx context.Context, obj *models.FaceGroup) (int, error) {
	//log.Println("TRACE ImageFaceCount", obj)
	db := r.DB(ctx)
	user := auth.UserFromContext(ctx)
	if user == nil {
		return -1, errors.New("unauthorized")
	}

	if face_detection.GlobalFaceDetector == nil {
		return -1, ErrFaceDetectorNotInitialized
	}

	if err := user.FillAlbums(db); err != nil {
		return -1, err
	}

	begin1 := time.Now()
	var count int64
	if utils.DevelopmentCheckSqlTiming() {
		userAlbumIDs := make([]int, len(user.Albums))
		for i, album := range user.Albums {
			userAlbumIDs[i] = album.ID
		}

		query := db.
			Model(&models.ImageFace{}).
			Joins("Media").
			Where(faceGroupIDIsQuestion, obj.ID).
			Where("album_id IN (?)", userAlbumIDs)

		if err := query.Count(&count).Error; err != nil {
			return -1, err
		}
	}
	time1 := time.Since(begin1)
	//log.Println("FaceGroup1", faceGroup.ID, "Time1", time1)
//////////////////////////////////////
	begin2 := time.Now()
	query2 := db.
		Model(&models.ImageFace{}).
		Joins("Media").
		Joins("LEFT JOIN user_albums ON Media.album_id = user_albums.album_id").Where("user_albums.user_id = ?", user.ID).
		Where(faceGroupIDIsQuestion, obj.ID)

	var count2 int64
	if err := query2.Count(&count2).Error; err != nil {
		return -1, err
	}
	if utils.DevelopmentCheckSqlTiming() {
		time2 := time.Since(begin2)
		sum1Cs += time1
		sum2Cs += time2
		if count != count2 {
			log.Println("ERROR ImageFaceCount", count, "!=", count2)
		} else {
			log.Println("TRACE ImageFaceCount", count, "Time1", time1, "Time2", time2, "Diff", time1 - time2)
			log.Println("TRACE DiffCs", sum1Cs - sum2Cs, "Sum1Cs", sum1Cs, "Sum2Cs", sum2Cs, "Diff %", 100 * float64(sum1Cs - sum2Cs) / float64(sum1Cs) )
			log.Println("TRACE DiffIs", sum1Is - sum2Is, "Sum1Is", sum1Is, "Sum2Is", sum2Is, "Diff %", 100 * float64(sum1Is - sum2Is) / float64(sum1Is) )
			log.Println("TRACE DiffMs", sum1Ms - sum2Ms, "Sum1Ms", sum1Ms, "Sum2Ms", sum2Ms, "Diff %", 100 * float64(sum1Ms - sum2Ms) / float64(sum1Ms) )
		}
	}
//////////////////////////////////////

	return int(count2), nil
}

// Media is the resolver for the media field.
func (r *imageFaceResolver) Media(ctx context.Context, obj *models.ImageFace) (*models.Media, error) {
	if err := obj.FillMedia(r.DB(ctx)); err != nil {
		return nil, err
	}

	return &obj.Media, nil
}

// FaceGroup is the resolver for the faceGroup field.
func (r *imageFaceResolver) FaceGroup(ctx context.Context, obj *models.ImageFace) (*models.FaceGroup, error) {
	//log.Println("FaceGroup", obj)
	if obj.FaceGroup != nil {
		return obj.FaceGroup, nil
	}

	if face_detection.GlobalFaceDetector == nil {
		return nil, ErrFaceDetectorNotInitialized
	}

	var faceGroup models.FaceGroup
	if err := r.DB(ctx).Model(&obj).Association("FaceGroup").Find(&faceGroup); err != nil {
		return nil, err
	}

	obj.FaceGroup = &faceGroup

	return &faceGroup, nil
}

// SetFaceGroupLabel is the resolver for the setFaceGroupLabel field.
func (r *mutationResolver) SetFaceGroupLabel(ctx context.Context, faceGroupID int, label *string) (*models.FaceGroup, error) {
	db := r.DB(ctx)
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, errors.New("unauthorized")
	}

	if face_detection.GlobalFaceDetector == nil {
		return nil, ErrFaceDetectorNotInitialized
	}

	faceGroup, err := userOwnedFaceGroup(db, user, faceGroupID)
	if err != nil {
		return nil, err
	}

	if err := db.Model(faceGroup).Update("label", label).Error; err != nil {
		return nil, err
	}

	return faceGroup, nil
}

// CombineFaceGroups is the resolver for the combineFaceGroups field.
func (r *mutationResolver) CombineFaceGroups(ctx context.Context, destinationFaceGroupID int, sourceFaceGroupIDs []int) (*models.FaceGroup, error) {
	db := r.DB(ctx)
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, errors.New("unauthorized")
	}

	if face_detection.GlobalFaceDetector == nil {
		return nil, ErrFaceDetectorNotInitialized
	}

	if len(sourceFaceGroupIDs) < 1 {
		return nil, errors.New("at least one source face group ID is required")
	}

	destinationFaceGroup, err := userOwnedFaceGroup(db, user, destinationFaceGroupID)
	if err != nil {
		return nil, err
	}

	var sourceFaceGroups []*models.FaceGroup

	// Validate the source groups before beginning the merge
	for _, sourceID := range sourceFaceGroupIDs {
		if sourceID == destinationFaceGroup.ID {
			return nil, errors.New("source face groups cannot include the destination face group")
		}

		// Ensure the user owns at least one picture with each source
		sourceFaceGroup, err := userOwnedFaceGroup(db, user, sourceID)
		if err != nil {
			return nil, err
		}

		sourceFaceGroups = append(sourceFaceGroups, sourceFaceGroup)
	}

	// Perform the merge
	updateError := db.Transaction(func(tx *gorm.DB) error {
		faceGroupIDs := append([]int{destinationFaceGroup.ID}, sourceFaceGroupIDs...)
		hasDuplicateMedia, err := hasDuplicateMediaInFaceGroupsUnion(tx, faceGroupIDs...)
		if err != nil {
			return err
		}
		if hasDuplicateMedia {
			return errors.New("cannot merge face groups because the destination would contain duplicate images")
		}

		if err := tx.
			Model(&models.ImageFace{}).
			Where(faceGroupIDsInQuestion, sourceFaceGroupIDs).
			Update("face_group_id", destinationFaceGroup.ID).Error; err != nil {
			return err
		}

		// delete the source face groups
		if err := deleteFaceGroups(sourceFaceGroups, tx); err != nil {
			return err
		}
		subQuery := tx.Model(&models.ImageFace{}).
			Select("MIN(id)").
			Where("face_group_id = ?", destinationFaceGroup.ID).
			Group("media_id")

		err = tx.Where("face_group_id = ?", destinationFaceGroup.ID).
			Where("id NOT IN (?)", subQuery).
			Delete(&models.ImageFace{}).
			Error
		if err != nil {
			return err
		}
		return nil
	})

	if updateError != nil {
		return nil, updateError
	}

	face_detection.GlobalFaceDetector.MergeImageFaces(sourceFaceGroupIDs, int32(destinationFaceGroupID))

	return destinationFaceGroup, nil
}

// MoveImageFaces is the resolver for the moveImageFaces field.
func (r *mutationResolver) MoveImageFaces(ctx context.Context, imageFaceIDs []int, destinationFaceGroupID int) (*models.FaceGroup, error) {
	db := r.DB(ctx)
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, errors.New("unauthorized")
	}

	if face_detection.GlobalFaceDetector == nil {
		return nil, ErrFaceDetectorNotInitialized
	}

	userOwnedImageFaceIDs := make([]int, 0)
	var destFaceGroup *models.FaceGroup

	transErr := db.Transaction(func(tx *gorm.DB) error {

		var err error
		destFaceGroup, err = userOwnedFaceGroup(tx, user, destinationFaceGroupID)
		if err != nil {
			return err
		}

		userOwnedImageFaces, err := getUserOwnedImageFaces(tx, user, imageFaceIDs)
		if err != nil {
			return err
		}

		for _, imageFace := range userOwnedImageFaces {
			userOwnedImageFaceIDs = append(userOwnedImageFaceIDs, imageFace.ID)
		}

		hasDuplicateMedia, err := doesFaceGroupContainImages(tx, destFaceGroup.ID, userOwnedImageFaceIDs)
		if err != nil {
			return err
		}
		if hasDuplicateMedia {
			return errors.New("cannot move faces because the destination would contain duplicate images")
		}

		var sourceFaceGroups []*models.FaceGroup
		if err := tx.
			Joins("LEFT JOIN image_faces ON image_faces.face_group_id = face_groups.id").
			Where(imageFacesIDInQuestion, userOwnedImageFaceIDs).
			Find(&sourceFaceGroups).Error; err != nil {
			return err
		}

		if err := tx.
			Model(&models.ImageFace{}).
			Where("id IN (?)", userOwnedImageFaceIDs).
			Update("face_group_id", destFaceGroup.ID).Error; err != nil {
			return err
		}

		// delete face groups if they have become empty
		if err := deleteEmptyFaceGroups(sourceFaceGroups, tx); err != nil {
			return err
		}

		return nil
	})

	if transErr != nil {
		return nil, transErr
	}

	face_detection.GlobalFaceDetector.MergeImageFaces(userOwnedImageFaceIDs, int32(destFaceGroup.ID))

	return destFaceGroup, nil
}

// RecognizeUnlabeledFaces is the resolver for the recognizeUnlabeledFaces field.
func (r *mutationResolver) RecognizeUnlabeledFaces(ctx context.Context) ([]*models.ImageFace, error) {
	db := r.DB(ctx)
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, errors.New("unauthorized")
	}

	if face_detection.GlobalFaceDetector == nil {
		return nil, ErrFaceDetectorNotInitialized
	}

	var updatedImageFaces []*models.ImageFace

	transactionError := db.Transaction(func(tx *gorm.DB) error {
		var err error
		updatedImageFaces, err = face_detection.GlobalFaceDetector.RecognizeUnlabeledFaces(tx, user)

		return err
	})

	if transactionError != nil {
		return nil, transactionError
	}

	return updatedImageFaces, nil
}

// DetachImageFaces is the resolver for the detachImageFaces field.
func (r *mutationResolver) DetachImageFaces(ctx context.Context, imageFaceIDs []int) (*models.FaceGroup, error) {
	db := r.DB(ctx)
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, errors.New("unauthorized")
	}

	if face_detection.GlobalFaceDetector == nil {
		return nil, ErrFaceDetectorNotInitialized
	}

	userOwnedImageFaceIDs := make([]int, 0)
	newFaceGroup := models.FaceGroup{}

	transactionError := db.Transaction(func(tx *gorm.DB) error {

		userOwnedImageFaces, err := getUserOwnedImageFaces(tx, user, imageFaceIDs)
		if err != nil {
			return err
		}

		for _, imageFace := range userOwnedImageFaces {
			userOwnedImageFaceIDs = append(userOwnedImageFaceIDs, imageFace.ID)
		}

		if err := tx.Save(&newFaceGroup).Error; err != nil {
			return err
		}

		if err := tx.
			Model(&models.ImageFace{}).
			Where("id IN (?)", userOwnedImageFaceIDs).
			Update("face_group_id", newFaceGroup.ID).Error; err != nil {
			return err
		}

		return nil
	})

	if transactionError != nil {
		return nil, transactionError
	}

	face_detection.GlobalFaceDetector.MergeImageFaces(userOwnedImageFaceIDs, int32(newFaceGroup.ID))

	return &newFaceGroup, nil
}

// MyFaceGroups is the resolver for the myFaceGroups field.
func (r *queryResolver) MyFaceGroups(ctx context.Context, paginate *models.Pagination) ([]*models.FaceGroup, error) {
	//log.Println("TRACE MyFaceGroups", paginate)
	db := r.DB(ctx)
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, errors.New("unauthorized")
	}

	if face_detection.GlobalFaceDetector == nil {
		return nil, ErrFaceDetectorNotInitialized
	}

	begin1 := time.Now()
	var count int
	if utils.DevelopmentCheckSqlTiming() {
		if err := user.FillAlbums(db); err != nil {
			return nil, err
		}

		userAlbumIDs := make([]int, len(user.Albums))
		for i, album := range user.Albums {
			userAlbumIDs[i] = album.ID
		}

		faceGroupQuery := db.
			Joins("JOIN image_faces ON image_faces.face_group_id = face_groups.id").
			Where("image_faces.media_id IN (?)",
				db.Select("media.id").Table("media").Where(mediaAlbumIDInQuestion, userAlbumIDs)).
			Group("image_faces.face_group_id").
			Group("face_groups.id").
			Order("CASE WHEN label IS NULL THEN 1 ELSE 0 END").
			Order("COUNT(image_faces.id) DESC")

		faceGroupQuery = models.FormatSQL(faceGroupQuery, nil, paginate)

		var faceGroups []*models.FaceGroup
		if err := faceGroupQuery.Find(&faceGroups).Error; err != nil {
			return nil, err
		}
		count = len(faceGroups)
	}
	time1 := time.Since(begin1)
	//log.Println("MyFaceGroups1", len(faceGroups), "Time1", time1)
//////////////////////////////////////
	begin2 := time.Now()
	faceGroupQuery2 := db.
		Joins("JOIN image_faces ON image_faces.face_group_id = face_groups.id").
		Where("image_faces.media_id IN (?)",
			db.Select("media.id").Table("media").Joins("JOIN user_albums ON user_albums.album_id = media.album_id").Where("user_albums.user_id = ?", user.ID)).
		Group("image_faces.face_group_id").
		Group("face_groups.id").
		Order("CASE WHEN label IS NULL THEN 1 ELSE 0 END").
		Order("COUNT(image_faces.id) DESC")

	faceGroupQuery2 = models.FormatSQL(faceGroupQuery2, nil, paginate)

	var faceGroups2 []*models.FaceGroup
	if err := faceGroupQuery2.Find(&faceGroups2).Error; err != nil {
		return nil, err
	}
	if utils.DevelopmentCheckSqlTiming() {
		time2 := time.Since(begin2)
		sum1Ms += time1
		sum2Ms += time2
		if count != len(faceGroups2) {
			log.Println("ERROR MyFaceGroups len", count, "!=", len(faceGroups2))
		} else {
			log.Println("TRACE MyFaceGroups len", count, "MyFaceGroups2 len", len(faceGroups2), "Time1", time1, "Time2", time2, "Diff", time1 - time2)
			log.Println("TRACE DiffCs", sum1Cs - sum2Cs, "Sum1Cs", sum1Cs, "Sum2Cs", sum2Cs, "Diff %", 100 * float64(sum1Cs - sum2Cs) / float64(sum1Cs) )
			log.Println("TRACE DiffIs", sum1Is - sum2Is, "Sum1Is", sum1Is, "Sum2Is", sum2Is, "Diff %", 100 * float64(sum1Is - sum2Is) / float64(sum1Is) )
			log.Println("TRACE DiffMs", sum1Ms - sum2Ms, "Sum1Ms", sum1Ms, "Sum2Ms", sum2Ms, "Diff %", 100 * float64(sum1Ms - sum2Ms) / float64(sum1Ms) )
		}
	}
//////////////////////////////////////

	return faceGroups2, nil
}

// FaceGroup is the resolver for the faceGroup field.
func (r *queryResolver) FaceGroup(ctx context.Context, id int) (*models.FaceGroup, error) {
	//log.Println("TRACE FaceGroup", id)
	db := r.DB(ctx)
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, errors.New("unauthorized")
	}

	if face_detection.GlobalFaceDetector == nil {
		return nil, ErrFaceDetectorNotInitialized
	}

	begin1 := time.Now()
	var fid int
	if utils.DevelopmentCheckSqlTiming() {
		if err := user.FillAlbums(db); err != nil {
			return nil, err
		}

		userAlbumIDs := make([]int, len(user.Albums))
		for i, album := range user.Albums {
			userAlbumIDs[i] = album.ID
		}

		faceGroupQuery := db.
			Joins("LEFT JOIN image_faces ON image_faces.face_group_id = face_groups.id").
			Joins("LEFT JOIN media ON image_faces.media_id = media.id").
			Where("face_groups.id = ?", id).
			Where(mediaAlbumIDInQuestion, userAlbumIDs)

		var faceGroup models.FaceGroup
		if err := faceGroupQuery.Find(&faceGroup).Error; err != nil {
			return nil, err
		}
		fid = faceGroup.ID
	}
	time1 := time.Since(begin1)
	//log.Println("FaceGroup1", faceGroup.ID, "Time1", time1)
//////////////////////////////////////
	begin2 := time.Now()
	faceGroupQuery2 := db.
		Joins("LEFT JOIN image_faces ON image_faces.face_group_id = face_groups.id").
		Joins("LEFT JOIN media ON image_faces.media_id = media.id").
		Joins("JOIN user_albums ON user_albums.album_id = media.album_id").Where("user_albums.user_id = ?", user.ID).
		Where("face_groups.id = ?", id)

	var faceGroup2 models.FaceGroup
	if err := faceGroupQuery2.Find(&faceGroup2).Error; err != nil {
		return nil, err
	}
	if utils.DevelopmentCheckSqlTiming() {
		time2 := time.Since(begin2)
		sum1Ms += time1
		sum2Ms += time2
		if fid != faceGroup2.ID {
			log.Println("ERROR FaceGroup", fid, "!=", faceGroup2.ID)
		} else {
			log.Println("TRACE FaceGroup", faceGroup2.ID, "Time1", time1, "Time2", time2, "Diff", time1 - time2)
			log.Println("TRACE DiffCs", sum1Cs - sum2Cs, "Sum1Cs", sum1Cs, "Sum2Cs", sum2Cs, "Diff %", 100 * float64(sum1Cs - sum2Cs) / float64(sum1Cs) )
			log.Println("TRACE DiffIs", sum1Is - sum2Is, "Sum1Is", sum1Is, "Sum2Is", sum2Is, "Diff %", 100 * float64(sum1Is - sum2Is) / float64(sum1Is) )
			log.Println("TRACE DiffMs", sum1Ms - sum2Ms, "Sum1Ms", sum1Ms, "Sum2Ms", sum2Ms, "Diff %", 100 * float64(sum1Ms - sum2Ms) / float64(sum1Ms) )
		}
	}
//////////////////////////////////////

	return &faceGroup2, nil
}

// FaceGroup returns api.FaceGroupResolver implementation.
func (r *Resolver) FaceGroup() api.FaceGroupResolver { return &faceGroupResolver{r} }

// ImageFace returns api.ImageFaceResolver implementation.
func (r *Resolver) ImageFace() api.ImageFaceResolver { return &imageFaceResolver{r} }

type (
	faceGroupResolver struct{ *Resolver }
	imageFaceResolver struct{ *Resolver }
)
